name: pebrapp
description: PEBRApp - The mobile app for the PEBRA trial in rural Lesotho.

version: 1.1.1-demo

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^1.1.0
  flushbar: ^1.8.0
  url_launcher: ^5.2.7
  shared_preferences: ^0.5.2
  spreadsheet_decoder: ^1.0.1
  password: ^1.0.0
  device_apps: 1.0.10

dev_dependencies:
  flutter_launcher_icons: ^0.7.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

# set the app launcher icon here, then to update the icon run
# `flutter packages pub run flutter_launcher_icons:main`
# https://pub.dartlang.org/packages/flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/logo/PEBRA_logo3_android.png'
#  image_path: "assets/logo/PEBRA_logo3_ios.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/excel/
